### ISSUE TITLE
ropsten faucet down

### ISSUE THREAD

**Issue by qx133** [locals-world/locals-faucetserver#1]
ropsten faucet seems to be down, tx id is shown but not broadcast to network

**Comment by kikipluche** [comment]
@sponnet is this the test ether faucet?

**Comment by sponnet** [comment]
I am currently re-syncing my geth node, hopefully thins fixes the problems. I will post a message here when it's back in sync.

**Comment by xiaoyao1991** [comment]
I'm experiencing the same issue here.

**Comment by sponnet** [comment]
switched from geth to parity , and that seems to work. example : https://ropsten.io/tx/0x727a8cb3400c38cfe3a03574d686a51cb80a44c11bcb1fa12eddd27748b4f431

Please let me know if you confirm that it works again.

**Comment by qx133** [comment]
working again for me. this faucet is a really great tool for the community!

**Comment by sponnet** [comment]
I haven't added it to the API docs yet , but if you see abuse ( ppl constantly sending tx's to suck the faucet empty ) you can just call /blacklist/<address> to blacklist any address.
